### ISSUE TITLE
RSSHub使用显示微博图片突然出错

### ISSUE THREAD

**Issue by LinxHex** [Rongronggg9/rsstt-img-relay#4]
https://github.com/DIYgod/RSSHub/issues/11096
根据之前的讨论成功显示了微博图片，但今天突然又开始不能显示了，错误如下，麻烦请看一下呢。
谢谢
![image](https://user-images.githubusercontent.com/92703641/201050022-a2c78bbf-31eb-4850-9499-8f39f1059811.png)
![image](https://user-images.githubusercontent.com/92703641/201050082-e0653a26-7b30-43c3-8d0b-611a5ae77a98.png)

**Comment by LinxHex** [comment]
![image](https://user-images.githubusercontent.com/92703641/201051317-b937e4aa-cc8e-4b8b-9139-f0190d8f3793.png)
![image](https://user-images.githubusercontent.com/92703641/201051362-3080b674-31bc-41a7-bc85-3222bc807bfc.png)
Emmm，可能是微博又在作妖了，wx1.sinaimg.cn不能显示，wx2.sinaimg.cn、wx3.sinaimg.cn、wx4.sinaimg.cn都可以正常显示。
是不是需要想办法把图片链接给换掉呀？

**Comment by ttxhxz** [comment]
> ![image](https://user-images.githubusercontent.com/92703641/201051317-b937e4aa-cc8e-4b8b-9139-f0190d8f3793.png) ![image](https://user-images.githubusercontent.com/92703641/201051362-3080b674-31bc-41a7-bc85-3222bc807bfc.png) Emmm，可能是微博又在作妖了，wx1.sinaimg.cn不能显示，wx2.sinaimg.cn、wx3.sinaimg.cn、wx4.sinaimg.cn都可以正常显示。 是不是需要想办法把图片链接给换掉呀？

请问这个参数在rsshub中如何用呢？我在创建docker的时候设置参数
`IMAGE_HOTLINK_TEMPLATE: 'https://xxx.workers.dev?url={url}'`
