### ISSUE TITLE
请问如何在RSSHub中使其对微博路由中的视频生效？

### ISSUE THREAD

**Issue by LinxHex** [Rongronggg9/rsstt-img-relay#6]
按照文档所说的方法配置后，对于视频的处理并未生效。
![image](https://github.com/Rongronggg9/rsstt-img-relay/assets/92703641/b73605c6-05cd-4a10-bd2a-1f9daef453a8)
![image](https://github.com/Rongronggg9/rsstt-img-relay/assets/92703641/eecd340f-ab7d-4a06-b3e3-c03bd52977d3)

且将部署的rsstt-img-relay服务的网址后面添加微博视频的链接，提示：
`{"code":415,"msg":"The keyword \"image , video , audio , application , font , model\" was whitelisted by the operator of this proxy, but got \"text/html\"."}`

请问是否有方法解决？

**Comment by Rongronggg9** [comment]
```
https://example.com/${href}
```

**Comment by LinxHex** [comment]
> ```
> https://example.com/${href}
> ```

这个我也尝试过，也是不生效😣

**Comment by Rongronggg9** [comment]
微博视频 CDN 的链接带有有效期。如果有效期已经过了，则无能为力。在阅读器刚刷新出来新的微博的时候，应是能看的。之后不行。

**Comment by Rongronggg9** [comment]
也有可能是我没有添加针对微博视频 CDN 的特殊处理，我再看看

**Comment by Rongronggg9** [comment]
7a62d7d32d9df737c5332ab6a5041cc74e95120e
